type User
{
    id:ID!
    name:String
    email:String
    address:String
    role:String
    createdAt:String
    updatedAt:String
}

type AuthPayload
{
    token:String!
    user:User!
}

input AuthInput
{
    email:String!
    password:String!
}

input UserInput
{
    name:String
    email:String
    password:String
    address:String
}

type Query
{
    allUsers:[User]!
    getUser(id:ID!):User!
}

type Mutation
{
    register(userInput:UserInput):AuthPayload!
    login(authInput:AuthInput!):AuthPayload!
    addUser(userInput:UserInput):User!
    updateUser(id:ID!,userInput:UserInput):User!
    deleteUser(id:ID!):String


}