spring.application.name=Microservices-Architechture

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/architechture
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.graphql.http.path=/graphql
spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql
spring.graphql.schema.locations=classpath:graphql/

# Server
server.port=8081

# JWT
jwt.secret=your-super-long-secret-key-for-jwt-signing-min-32-chars
jwt.expiration=86400000 